server:
  port: 6996

spring:
  application:
    name: checkout-demo

  datasource:
    url: jdbc:postgresql://localhost:5432/checkout_demo
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

  threads:
    virtual:
      enabled: true

logging:
  level:
    org.hibernate.SQL: debug